version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build:
      context: .
    container_name: schedule-service-dev
    hostname: schedule-service
    volumes:
      - nodemodules-schedule-services:/home/node/schedule-services/node_modules
      - .:/home/node/schedule-services
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    working_dir: /home/node/schedule-services
    ports:
      - 5001:5001
volumes:
  db:
  nodemodules-schedule-services:
    external: true